// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi4zJ6TobAKVTB9sfTXAopG1W5KBmTEg8',
    appId: '1:193832834701:web:ddb6d72f9e3fc274e074c4',
    messagingSenderId: '193832834701',
    projectId: 'linkup-app-3d672',
    authDomain: 'linkup-app-3d672.firebaseapp.com',
    storageBucket: 'linkup-app-3d672.firebasestorage.app',
    measurementId: 'G-DK0QP86X7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5kGr1VcsOhgYuA_Fys1ZvbSS6pKd89LA',
    appId: '1:193832834701:android:87cbab084f075dc3e074c4',
    messagingSenderId: '193832834701',
    projectId: 'linkup-app-3d672',
    storageBucket: 'linkup-app-3d672.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzjXs1kV_0hHOznsPWs6jAw1OQ_2aYR14',
    appId: '1:193832834701:ios:d083305db0e8ebc3e074c4',
    messagingSenderId: '193832834701',
    projectId: 'linkup-app-3d672',
    storageBucket: 'linkup-app-3d672.firebasestorage.app',
    iosBundleId: 'com.example.linkupApp',
  );

}